openapi: 3.0.0
info:
  title: Workflow Execution Service
  contact: {}
  version: '1.0.1'
  x-logo:
    url: 'https://www.ga4gh.org/wp-content/themes/ga4gh-theme/gfx/GA-logo-horizontal-tag-RGB.svg'
  description:
    $ref: ./tags/exec_summary.md
servers:
- url: https://{defaultHost}/{basePath}/{apiVersion}
  variables:
    defaultHost:
      default: www.example.com
    basePath:
      default: ga4gh/wes
    apiVersion:
      default: v1
tags:
  - name: Service Info
    description: Get information about the workflow execution service
  - name: Workflow Runs
    description: Submit and monitor workflows in a WES environment
  - name: Introduction
    description:
      $ref: ./tags/introduction.md
  - name: Authorization & Authentication
    description:
      $ref: ./tags/auth.md
  - name: serviceinfo_model
    x-displayName: ServiceInfo
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/ServiceInfo" />
  - name: runlistresponse_model
    x-displayName: RunListResponse
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/RunListResponse" />
  - name: runid_model
    x-displayName: RunId
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/RunId" />
  - name: state_model
    x-displayName: State
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/State" />
  - name: runstatus_model
    x-displayName: RunStatus
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/RunStatus" />
  - name: runrequest_model
    x-displayName: RunRequest
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/RunRequest" />
  - name: runlog_model
    x-displayName: RunLog
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/RunLog" />
  - name: log_model
    x-displayName: Log
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Log" />
  - name: defaultworkflowengineparameter_model
    x-displayName: DefaultWorkflowEngineParameter
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/DefaultWorkflowEngineParameter" />
  - name: workflowtypeversion_model
    x-displayName: WorkflowTypeVersion
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/WorkflowTypeVersion" />
x-tagGroups:
  - name: Overview
    tags:
      - Introduction
      - Authorization & Authentication
  - name: Operations
    tags:
      - Service Info
      - Workflow Runs
  - name: Models
    tags:
      - serviceinfo_model
      - runlistresponse_model
      - runid_model
      - state_model
      - runstatus_model
      - runrequest_model
      - runlog_model
      - log_model
      - defaultworkflowengineparameter_model
      - workflowtypeversion_model
paths:
  /service-info:
    $ref: ./paths/service-info.yaml
  /runs:
    $ref: ./paths/runs.yaml
  '/runs/{run_id}':
    $ref: ./paths/runs@{run_id}.yaml
  '/runs/{run_id}/status':
    $ref: ./paths/runs@{run_id}@status.yaml
  '/runs/{run_id}/cancel':
    $ref: ./paths/runs@{run_id}@cancel.yaml
components:
  schemas:
    ServiceInfo:
      $ref: ./components/schemas/ServiceInfo.yaml
    RunId:
      $ref: ./components/schemas/RunId.yaml
    State:
      $ref: ./components/schemas/State.yaml
    RunStatus:
      $ref: ./components/schemas/RunStatus.yaml
    RunRequest:
      $ref: ./components/schemas/RunRequest.yaml
    RunLog:
      $ref: ./components/schemas/RunLog.yaml
    Log:
      $ref: ./components/schemas/Log.yaml
    DefaultWorkflowEngineParameter:
      $ref: ./components/schemas/DefaultWorkflowEngineParameter.yaml
    WorkflowTypeVersion:
      $ref: ./components/schemas/WorkflowTypeVersion.yaml
    RunListResponse:
      $ref: ./components/schemas/RunListResponse.yaml
    ErrorResponse:
      $ref: ./components/schemas/ErrorResponse.yaml







